/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainScreen.java
 *
 * Created on Feb 28, 2012, 6:26:06 PM
 */
package factory.ranger.view;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author axioo
 */
public class MainForm extends javax.swing.JFrame {

    private static MainForm mainform = new MainForm();
    
    public static MainForm getSingleton(){
        return mainform;
    }
    /** Creates new form MainScreen */
    public MainForm() {
        initComponents();
        
        MainScreen.getSingleton().setBounds(0, 0, 800, 600);
        this.add(MainScreen.getSingleton());
        MainScreen.getSingleton().setVisible(true);
        
        SelectScreen.getSingleton().setBounds(0, 0, 800, 600);
        this.add(SelectScreen.getSingleton());
        SelectScreen.getSingleton().setVisible(false);
        
        RecapScreen.getSingleton().setBounds(0, 0, 800, 600);
        this.add(RecapScreen.getSingleton());
        RecapScreen.getSingleton().setVisible(false);
        
        SimulationScreen.getSingleton().setBounds(0, 0, 800, 600);
        this.add(SimulationScreen.getSingleton());
        SimulationScreen.getSingleton().setVisible(false);
        
        ResultScreen.getSingleton().setBounds(0, 0, 800, 600);
        this.add(ResultScreen.getSingleton());
        ResultScreen.getSingleton().setVisible(false);
        
        this.setVisible(false);
        this.setTitle("Factory Ranger");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
