/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulationPanel.java
 *
 * Created on Feb 29, 2012, 3:54:21 AM
 */
package factory.ranger.view;

import factory.ranger.utility.SimTimer;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;

/**
 *
 * @author axioo
 */
public class SimulationScreen extends javax.swing.JPanel {

    private static SimulationScreen simscreen = new SimulationScreen();
    
    public static SimulationScreen getSingleton(){
        return simscreen;
    }
    
    LogRoutePanel logRoute;
    LogSchedulePanel logSchedule;
    SimRoutingPanel simRoute;
    JScrollPane content;
    /** Creates new form SimulationPanel */
    public SimulationScreen() {
        initComponents();
    }
    
    public JScrollPane getContent(){
        return content;
    }
     
    public void displaySimulation(int mode) throws IOException{
        sim_routing.setVisible(false);
        sim_scheduling.setVisible(false);
        log_routing.setVisible(false);
        log_scheduling.setVisible(false);
        
        switch (mode){
            case 1 :
                sim_routing.setVisible(true);
                showSimRoute();
//                ibudget_txt.setText(SelectScreen.getSingleton().path);
//                if(SelectScreen.getSingleton().mode == 1){
//                    income_txt.setText("Breadth First Search (BFS)");
//                } else if(SelectScreen.getSingleton().mode == 2){
//                    income_txt.setText("Depth First Search (DFS)");
//                } else if(SelectScreen.getSingleton().mode == 3){
//                    income_txt.setText("A* Algorithm");
//                }
                //FormPanel.state = 2;
                break;
            case 2 :
                sim_scheduling.setVisible(true);
                
                //FormPanel.state = 3;
                break;
            case 3 :
                log_routing.setVisible(true);
                showLogRoute();
                //showWork();
                //FormPanel.state = 4;
                break;
            case 4 :
                log_scheduling.setVisible(true);
                showLogSchedule();
                //showSold();
                //FormPanel.state = 5;
                break;
            default :
                
                break;
        }
        this.setVisible(true);
        
    }
    
    public void hideSimulation(){
        sim_routing.setVisible(true);
        sim_scheduling.setVisible(true);
        log_routing.setVisible(true);
        log_scheduling.setVisible(true);
        this.setVisible(false);
    }
    
    public void showSimRoute() throws IOException{
        sim_routing.removeAll();
        simRoute = new SimRoutingPanel();
        content = new JScrollPane();
        content.setOpaque(false);
        content.getVerticalScrollBar().setBlockIncrement(100);
        content = simRoute.getContent();
        content.setBounds(158,8,625,410);
        content.setVisible(true);
        sim_routing.add(jLabel17);
        sim_routing.add(jLabel18);
        sim_routing.add(content);
        System.out.println("aa");
        this.setVisible(true);
    }
    
    public void showLogRoute() throws IOException{
        log_routing.removeAll();
        logRoute = new LogRoutePanel();
        content = new JScrollPane();
        content.setOpaque(false);
        content.getVerticalScrollBar().setBlockIncrement(100);
        content = logRoute.getContent();
        content.setBounds(158,8,625,410);
        content.setVisible(true);
        log_routing.add(jLabel20);
        log_routing.add(jLabel19);
        log_routing.add(content);
        this.setVisible(true);
    }
    
    public void showLogSchedule() throws IOException{
        log_scheduling.removeAll();
        logSchedule = new LogSchedulePanel();
        content = new JScrollPane();
        content.setOpaque(false);
        content.getVerticalScrollBar().setBlockIncrement(100);
        content = logSchedule.getContent();
        content.setBounds(158,8,625,410);
        content.setVisible(true);
        log_scheduling.add(jLabel24);
        log_scheduling.add(jLabel23);
        log_scheduling.add(content);
        this.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        sim_routing = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sim_scheduling = new javax.swing.JLayeredPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        log_routing = new javax.swing.JLayeredPane();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        log_scheduling = new javax.swing.JLayeredPane();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        log_scheduling_btn = new javax.swing.JLabel();
        log_route_btn = new javax.swing.JLabel();
        sim_schedule_btn = new javax.swing.JLabel();
        sim_route_btn = new javax.swing.JLabel();
        skip_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel17.setForeground(new java.awt.Color(229, 224, 181));
        jLabel17.setText("route finding");
        jLabel17.setBounds(20, 90, 120, 35);
        sim_routing.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu selected-x10y120.png"))); // NOI18N
        jLabel18.setText("jLabel5");
        jLabel18.setBounds(10, 80, 140, 55);
        sim_routing.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sim_routing.setBounds(0, 100, 800, 430);
        jLayeredPane1.add(sim_routing, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel22.setForeground(new java.awt.Color(229, 224, 181));
        jLabel22.setText("scheduling");
        jLabel22.setBounds(40, 160, 120, 35);
        sim_scheduling.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu selected-x10y120.png"))); // NOI18N
        jLabel21.setText("jLabel5");
        jLabel21.setBounds(10, 150, 140, 55);
        sim_scheduling.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sim_scheduling.setBounds(0, 100, 800, 430);
        jLayeredPane1.add(sim_scheduling, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel20.setForeground(new java.awt.Color(229, 224, 181));
        jLabel20.setText("route finding");
        jLabel20.setBounds(20, 300, 120, 35);
        log_routing.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu selected-x10y120.png"))); // NOI18N
        jLabel19.setText("jLabel5");
        jLabel19.setBounds(10, 290, 140, 55);
        log_routing.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        log_routing.setBounds(0, 100, 800, 430);
        jLayeredPane1.add(log_routing, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel24.setForeground(new java.awt.Color(229, 224, 181));
        jLabel24.setText("scheduling");
        jLabel24.setBounds(40, 370, 120, 35);
        log_scheduling.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu selected-x10y120.png"))); // NOI18N
        jLabel23.setText("jLabel5");
        jLabel23.setBounds(10, 360, 140, 55);
        log_scheduling.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        log_scheduling.setBounds(0, 100, 800, 430);
        jLayeredPane1.add(log_scheduling, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel16.setForeground(new java.awt.Color(229, 224, 181));
        jLabel16.setText("simulation");
        jLabel16.setBounds(20, 120, 120, 35);
        jLayeredPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu selected-x10y120.png"))); // NOI18N
        jLabel15.setText("jLabel5");
        jLabel15.setBounds(10, 110, 140, 55);
        jLayeredPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel13.setForeground(new java.awt.Color(229, 224, 181));
        jLabel13.setText("process log");
        jLabel13.setBounds(20, 330, 120, 35);
        jLayeredPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu selected-x10y120.png"))); // NOI18N
        jLabel14.setText("jLabel5");
        jLabel14.setBounds(10, 320, 140, 55);
        jLayeredPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel9.setForeground(new java.awt.Color(229, 224, 181));
        jLabel9.setText("route finding");
        jLabel9.setBounds(40, 400, 120, 35);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel10.setForeground(new java.awt.Color(229, 224, 181));
        jLabel10.setText("scheduling");
        jLabel10.setBounds(50, 470, 100, 35);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel8.setForeground(new java.awt.Color(229, 224, 181));
        jLabel8.setText("route finding");
        jLabel8.setBounds(40, 190, 120, 35);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel7.setForeground(new java.awt.Color(229, 224, 181));
        jLabel7.setText("scheduling");
        jLabel7.setBounds(60, 260, 100, 35);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-result btn x610y545.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBounds(610, 610, 180, 46);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-right menu-x150y100.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBounds(150, 100, 640, 430);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/title.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(0, 0, 800, 80);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        log_scheduling_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu-x10y120.png"))); // NOI18N
        log_scheduling_btn.setText("jLabel5");
        log_scheduling_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_scheduling_btnMouseClicked(evt);
            }
        });
        log_scheduling_btn.setBounds(30, 460, 140, 55);
        jLayeredPane1.add(log_scheduling_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        log_route_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu-x10y120.png"))); // NOI18N
        log_route_btn.setText("jLabel5");
        log_route_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_route_btnMouseClicked(evt);
            }
        });
        log_route_btn.setBounds(30, 390, 140, 55);
        jLayeredPane1.add(log_route_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sim_schedule_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu-x10y120.png"))); // NOI18N
        sim_schedule_btn.setText("jLabel5");
        sim_schedule_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sim_schedule_btnMouseClicked(evt);
            }
        });
        sim_schedule_btn.setBounds(30, 250, 140, 55);
        jLayeredPane1.add(sim_schedule_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sim_route_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-left menu-x10y120.png"))); // NOI18N
        sim_route_btn.setText("jLabel5");
        sim_route_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sim_route_btnMouseClicked(evt);
            }
        });
        sim_route_btn.setBounds(30, 180, 140, 55);
        jLayeredPane1.add(sim_route_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        skip_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/simulation-result btn x610y545.png"))); // NOI18N
        skip_btn.setText("jLabel5");
        skip_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skip_btnMouseClicked(evt);
            }
        });
        skip_btn.setBounds(600, 540, 180, 50);
        jLayeredPane1.add(skip_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factory/ranger/image/main-bg.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void skip_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skip_btnMouseClicked
        // TODO add your handling code here:
        hideSimulation();
        try {
            ResultScreen.getSingleton().displayResult(1);
        } catch (IOException ex) {
            Logger.getLogger(SimulationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_skip_btnMouseClicked

    private void log_scheduling_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_scheduling_btnMouseClicked
        try {
            // TODO add your handling code here:
            displaySimulation(4);
            System.out.println("aaa");
        } catch (IOException ex) {
            Logger.getLogger(SimulationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_log_scheduling_btnMouseClicked

    private void log_route_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_route_btnMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            displaySimulation(3);
        } catch (IOException ex) {
            Logger.getLogger(SimulationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_log_route_btnMouseClicked

    private void sim_schedule_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sim_schedule_btnMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            displaySimulation(2);
        } catch (IOException ex) {
            Logger.getLogger(SimulationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sim_schedule_btnMouseClicked

    private void sim_route_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sim_route_btnMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            displaySimulation(1);
        } catch (IOException ex) {
            Logger.getLogger(SimulationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimTimer timer;
        timer = new SimTimer(2*1000);
        timer.start();
    }//GEN-LAST:event_sim_route_btnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel log_route_btn;
    private javax.swing.JLayeredPane log_routing;
    private javax.swing.JLayeredPane log_scheduling;
    private javax.swing.JLabel log_scheduling_btn;
    private javax.swing.JLabel sim_route_btn;
    private javax.swing.JLayeredPane sim_routing;
    private javax.swing.JLabel sim_schedule_btn;
    private javax.swing.JLayeredPane sim_scheduling;
    private javax.swing.JLabel skip_btn;
    // End of variables declaration//GEN-END:variables
}
